### ISSUE TITLE
Unexpected behaviuor in case of lexicographically consecutive strings

### ISSUE THREAD

**Issue by delfrrr** [fasiha/mudderjs#2]
Current behavior 
```
mudder.alphabet.mudder('a', 'aa', 1);
//[ 'aaa' ]
```

Expected behavior would be to throw exception

**Comment by fasiha** [comment]
A thousand apologies for not thinking of this when writing the lib. I knew it was an issue because [m69](https://stackoverflow.com/a/38927158/500207) explicitly called attention to it—“You should never create a string by appending an 'a' to the left string, because that would create two lexicographically consecutive strings“—but I forgot to account for it.

Fixed bug and added a test to ensure it doesn’t creep back in.

Many, many thanks for submitting this valuable bug report!
