### ISSUE TITLE
Funky Looking Results When Repeatedly Swapping

### ISSUE THREAD

**Issue by JonathanHope** [fasiha/mudderjs#26]
First of all I can't even imagine how you figured everything for this library out. Awesome work!

I'm seeing some behavior that is likely expected, but still a little funky looking. If I repeatedly swap two items around the strings become long and repetitive very quickly. Take this code sample:

```
function swap() {
    const items = mudder.base62.mudder(undefined, undefined, 4, undefined, 10000, 4);
    for (var i = 0; i < 100; i++) {
        items[2] = mudder.base62.mudder(items[0], items[1], 1, undefined, undefined, 4)[0];
        items.sort()
    }
    console.log(items)
}
```

Running that yields the following results:

```
[
  '00Npd',
  '00Npd00000000000000003',
  '00Npd00000000000000007',
  '01XKX'
]
```

Basically the two strings very quickly converge on element 0. This use case is pretty synthetic, but I wanted to check that this was expected.

**Comment by fasiha** [comment]
Hi, thanks for writing! Yes this is expected I think, and the easiest way to see why is to notice that your example is functionally equivalent to this:
```js
let x = undefined;
for (let i = 0; i < 100; i++) {
  x = mudder.base62.mudder("a", x)[0];
  console.log(x);
}
```
The `numDivisions` argument doesn't really help us in this case because we're just recursively, logarithmically subdividing the space over and over, a hundred times. In other words, whether we recursively ask for the 50-percentile or 10-percentile or 90-percentile between 0 and 1, we're going to end up with 0.5**100 or 0.1**100 or 0.9**100 after a hundred iterations, and all those are pathological cases.

Hope this helps! Let me know if I misunderstood something.

**Comment by JonathanHope** [comment]
Thanks for getting back to me! That makes sense. It is a good reminder that I should add a rebalance feature though.
